# Generated by Django 2.2.12 on 2020-05-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=45)),
                ('distribuidora', models.CharField(max_length=45)),
            ],
        ),
    ]
