# Generated by Django 2.2.12 on 2020-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='estoque',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
