# Generated by Django 2.2.12 on 2020-05-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_jogo_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='categoria',
        ),
    ]
